import { lazy } from "react";
import { ROLES } from "./constants";
export const privateRoutes =[
    {
        key: 'dashboard',
        path: "/support",
        component: lazy(() => import("../pages/AdminSupport/AdminSupportDashboard")),
        allowedRoles: [ROLES.ADMIN_Support],
    },
    {
        key: 'homepage',
        path: '/home',
       // component: UserDashboard,
       component: lazy(() => import("../components/views/HomePage")),
        allowedRoles: [ROLES.USER],
    },
    // {
    //     key: 'timeline-transaction',
    //     path: '/timeline-transaction',
    //    // component: UserDashboard,
    //    component: lazy(() => import("../pages/Users/TimelineTransaction")),
    //     allowedRoles: [ROLES.USER],
    // }, 
    {
        key: 'userDashboard',
        path: '/user',
       // component: UserDashboard,
       component: lazy(() => import("../components/views/UserDashboard")),
        allowedRoles: [ROLES.USER],
    },
    {
        key: 'Transfer',
        path: '/transfer',
       component: lazy(() => import("../components/views/Transfer")),
        allowedRoles: [ROLES.USER],
    },
    {
        key: 'transaction',
        path: '/transaction',
       // component: UserDashboard,
       component: lazy(() => import("../components/views/Transaction")),
        allowedRoles: [ROLES.USER],
    },
    {
        key: 'transaction-history',
        path: '/transaction-history',
       // component: UserDashboard,
       component: lazy(() => import("../pages/Transaction/TransactionsTablePage")),
        allowedRoles: [ROLES.USER],
    },
    {
        key: 'analytics',
        path: '/analytics',
       // component: UserDashboard,
       component: lazy(() => import("../components/views/Analytics")),
        allowedRoles: [ROLES.USER],
    },
    {
        key: 'Accounts',
        path: "/accounts",
        // component: SuperAdminDashboard,
        component: lazy(() =>import("../components/views/Accounts")),
        allowedRoles:[ROLES.USER],
    },
    {
        key: 'AccountAndCardPage',
        path: "/accounts-card",
        // component: SuperAdminDashboard,
        component: lazy(() =>import("../pages/Accounts/AccountAndCardPage")),
        allowedRoles:[ROLES.USER],
    },
    {
      key: 'Investments',
      path: "/investments",
     // component: BankManager,
     component: lazy(() => import("../components/views/Investments")),
      allowedRoles: [ROLES.USER],
  },
  {
    key: 'credit-cards',
    path: "/credit-cards",
   // component: BankManager,
   component: lazy(() => import("../components/views/Credit-Cards")),
    allowedRoles: [ROLES.USER],
},
{
    key: 'loans',
    path: "/loans",
   // component: BankManager,
   component: lazy(() => import("../components/views/Loans")),
    allowedRoles: [ROLES.USER],
},
{
    key: 'service',
    path: "/services",
   // component: BankManager,
   component: lazy(() => import("../components/views/Service")),
    allowedRoles: [ROLES.USER],
},
{
    key: 'setting',
    path: "/setting",
   // component: BankManager,
   component: lazy(() => import("../components/views/Settings")),
    allowedRoles: [ROLES.USER],
},
{
    key: 'message-list',
    path: "/messages",
   // component: BankManager,
   component: lazy(() => import("../pages/Messages/MessageList")),
    allowedRoles: [ROLES.USER],
},
{
    key: 'message-chatbox',
    path: "/message/:id",
   // component: BankManager,
   component: lazy(() => import("../pages/Messages/MessageChatBox")),
    allowedRoles: [ROLES.USER],
},
]